### ISSUE TITLE
Won't close after calling handyCollapse.open()

### ISSUE THREAD

**Issue by MattApril** [sk-rt/handy-collapse#12]
# Problem
So far handy-collapse has been great, so thank you. However, I just ran into an issue when using the javascript open method directly.

# Steps to re-create

1. create a simple collapse with one data-{namespace}-control="myID" and one data-{namespace}-content="myID"
2. It should be collapsed by default (no is-active class)
3. Add another button that calls handyCollapse.open('myID') when clicked
4. Click the button created in step 3, myID content will expand as expected
5. But now try using the original control created in step 1

## Expected Result
myID content should collapse, and be controlled normally by the main control (data-{namespace}-control="myID")

## Actual Result
myID content collapses and then instantly expands again when using the main control (data-{namespace}-control="myID")

Also note that the bug only occurs after the second button (created in step 3) is clicked.

**Comment by sk-rt** [comment]
@MattApril Thanks for reporting the issue:)
But I couldn't reproduce the bug in my environment.
Is the code below correct?

```
<!--html-->
<div data-hc-content="myID">...Conntent</div>
<button type="button" data-hc-control="myID">Controll</button>
<button type="button" id="customControll">OPEN myID</button>
```

```
// JavaScript
const handyCollapse = new HandyCollapse({
    closeOthers: false
});
document.querySelector("#customControll").addEventListener('click',()=>{
    handyCollapse.open('myID')
})
```

**Comment by MattApril** [comment]
I did have the same code, but was using it within the Unpoly framework and had it organized in an unusual way. After some testing I was able to re-organize it to work as expected. My mistake!




Thanks for the reply, and keep up the good work! :D
