### ISSUE TITLE
Radio button being unchecked when collapsed

### ISSUE THREAD

**Issue by MattApril** [sk-rt/handy-collapse#16]
Steps to recreate:

1. Add a radio button inside of a collapse container.
2. check the radio button
3. collapse the container and expand it again.

**Expected result:** the radio button is still checked
**Actual result:** the radio button is no longer checked

I discovered this bug in Chrome, but it does not happen in Safari. I did not test any other browsers. Only seems to affect radio buttons - no other input element. I suspected this could be some kind of chrome bug/feature, but I tested with some other collapse libraries and could not reproduce it.

**Comment by MattApril** [comment]
I just realized that I definitely have other radio buttons inside of collapse containers in my app, and they work fine. But I was able to recreate this directly on the demo website https://handy-collapse.netlify.app/, so I still think something is up. I will dig more and see what I can figure out..

**Comment by sk-rt** [comment]
@MattApril Thanks for reporting the issue.
This was a bug with `element.cloneNode()`.
This issue will be fixed in the next release.

**Comment by sk-rt** [comment]
This issue was fixed on `v1.0.4`.

**Comment by MattApril** [comment]
Awesome, thanks
