### ISSUE TITLE
HandyCollapse() is not a constructor

### ISSUE THREAD

**Issue by blocksera** [sk-rt/handy-collapse#28]
When building a Vue component with Rollup, the error `HandyCollapse is not a constructor` is thrown in the browser.
It works though when called like this: `new HandyCollapse.default()`. After some digging, the problem is fixed if the module is built with webpack configuration below.

```js
/* webpack.confg.js */
output: {
        path: esmOutputPath,
        publicPath: publicPath,
        filename: "[name].js",
        library: {
            type: 'umd',
            name: 'HandyCollapse',
            export: 'default',
            umdNamedDefine: true
        }
    }
```

Thought we'd share for anyone running into the same issue.

**Comment by sk-rt** [comment]
@blocksera 
Thank you for the useful issue.

This library is built as `common js` , but it looks like it's being read as an `es module`.

I plan to support ESM in the near future.
Once that is done, you will be able to choose which format is best for you to use.
