### ISSUE TITLE
Feature request: breakpoints

### ISSUE THREAD

**Issue by havardlj** [sk-rt/handy-collapse#30]
Would like to request adding breakpoints to the plugin to make responsive accordions easier to setup. I keep designing sites where accordions are used only for mobile menus, and I know how to setup this myself with handy collapse, but it would be a really nice feature. See https://swiperjs.com/swiper-api#param-breakpoints for example

**Comment by sk-rt** [comment]
To keep this library small, I would like to avoid implementing the `breakpoints` param.
Instead, I'll create a `destroy` method to support dynamic initialization.
