### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by brynzovskii** [sk-rt/handy-collapse#31]
The hidden content (links, buttons) inside collapsible area can be traversed by tab key. Expected behavior is to navigate over control buttons if the content is hidden.

**Comment by sk-rt** [comment]
> The hidden content (links, buttons) inside collapsible area can be traversed by tab key. 

I tried it, but the focus didn't go inside the hidden content.  Elements with ` visibility:hidden ` do not get focus.
